# theme = "Light"
# "Light" | "Dark" | "Moonfly" | "Oxocarbon"

# [button]
# radius = 3

# background_color_hex = ""
# text_color_hex = ""
# border_color_hex = ""

# background_color_hex_pressed = ""
# text_color_hex_pressed = ""
# border_color_hex_pressed = ""
