name: Rust CI

on:
  push:
    branches:
      - stable
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build
      run: cargo build --release

    - name: Upload binaries
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-binary
        path: target/release/your_binary_name

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.os }}-binary
        path: .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *-binary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}